
import { Store, Translation } from './types';

export const STORES: Store[] = [
  { id: 'amazon-sa', name: 'Amazon SA', nameAr: 'أمازون السعودية', logo: 'https://upload.wikimedia.org/wikipedia/commons/4/4a/Amazon_icon.svg', url: 'https://www.amazon.sa/', description: 'World of Amazon', descriptionAr: 'عالم أمازون بين يديك' },
  { id: 'shein', name: 'SHEIN', nameAr: 'شي إن', logo: '/public/Icons/shein.png', url: 'https://ar.shein.com/', description: 'Latest Fashion', descriptionAr: 'أحدث صيحات الموضة' },
  { id: 'noon', name: 'NOON', nameAr: 'نون', logo: '/public/Icons/noon.png', url: 'https://www.noon.com/', description: 'Everything here', descriptionAr: 'كل ما تحتاجه في مكان واحد' },
  { id: 'aliexpress', name: 'AliExpress', nameAr: 'علي إكسبريس', logo: '/public/Icons/AliExpress.png', url: 'https://www.aliexpress.com/', description: 'Global deals', descriptionAr: 'صفقات عالمية مذهلة' },
  { id: 'trendyol', name: 'Trendyol', nameAr: 'ترينديول', logo: '/public/Icons/trendyol.png', url: 'https://www.trendyol.com/', description: 'Turkish Quality', descriptionAr: 'الجودة والأناقة التركية' },
  { id: 'niceone', name: 'Nice One', nameAr: 'نايس ون', logo: '/public/Icons/', url: 'https://niceonesa.com/', description: 'Beauty products', descriptionAr: 'منتجات التجميل والعناية' },
  { id: 'assaf', name: 'Assaf Store', nameAr: 'عساف للعطور', logo: '/public/Icons/assaf.png', url: 'https://assaf.store/', description: 'Premium Perfumes', descriptionAr: 'عطور عساف الفاخرة' },
  { id: 'laverne', name: 'Laverne', nameAr: 'لافيرن', logo: '/public/Icons/', url: 'https://laverne.com.sa/', description: 'Luxury Scents', descriptionAr: 'أرقى عطور لافيرن' },
  { id: 'dakhon', name: 'Dakhon', nameAr: 'دخون الإماراتية', logo: '/public/Icons/Dkhon AlEmarat.png', url: 'https://dakhon.com/', description: 'Emirati Oud', descriptionAr: 'البخور والعطور الإماراتية' },
  { id: 'alezz', name: 'Al-Ezz Oud', nameAr: 'العز للعود', logo: '/public/Icons/alez.png', url: 'https://alezzoud.com/', description: 'Authentic Oud', descriptionAr: 'أفخم أنواع العود' },
  { id: '6thstreet', name: '6thStreet', nameAr: '6 ستريت', logo: '/public/Icons/', url: 'https://www.6thstreet.com/', description: 'Top Brands', descriptionAr: 'أرقى الماركات العالمية' },
  { id: 'iherb', name: 'iHerb', nameAr: 'إيهيرب', logo: '/public/Icons/', url: 'https://www.iherb.com/', description: 'Natural Health', descriptionAr: 'المكملات والعناية الصحية' },
  { id: 'salla', name: 'Salla', nameAr: 'منصة سلة', logo: 'https://salla.sa/assets/images/logo-light.svg', url: 'https://salla.sa/', description: 'Saudi Stores', descriptionAr: 'المتاجر السعودية المحلية' },
  { id: 'fordeal', name: 'Fordeal', nameAr: 'فورديل', logo: 'https://cdn.worldvectorlogo.com/logos/fordeal.svg', url: 'https://www.fordeal.com/', description: 'Global Shopping', descriptionAr: 'تسوق عالمي شامل' },
];

export const APP_LOGO = '/public/Icons/logo_collection.png';// Note: To use your custom logo, upload it as 'logo.png' to the root directory and change APP_LOGO back to "./logo.png"

export const SOCIAL_LINKS = {
  instagram: 'https://www.instagram.com/collection.yem?igsh=MXNla2JmMHI2MWdobQ==',
  facebook: 'https://www.facebook.com/collection.yemen.store?mibextid=wwXIfr&mibextid=wwXIfr',
  whatsapp: 'https://wa.me/967774757728',
  telegram: 'https://t.me/collection_yemen',
  x: 'https://x.com/collection_yemen'
};

export const BRIDE_CATEGORIES = [
  { id: 'dresses', name: 'Wedding Dresses', nameAr: 'فساتين زفاف' },
  { id: 'hairdresser', name: 'Hairdresser', nameAr: 'كوافير' },
  { id: 'cosmetics', name: 'Cosmetics', nameAr: 'أدوات تجميل' },
];

export const FLASH_SALE_END_TIME = "2026-03-15T00:00:00Z";

export const TRANSLATIONS: Translation = {
  welcome: { en: 'Collection', ar: 'Collection' },
  aboutUs: { en: 'About Us', ar: 'من نحن' },
  aboutUsDesc: { en: 'Collection is your premier logistics partner in Yemen, bridging the gap between global markets and local convenience. We specialize in international purchasing and secure delivery.', ar: 'كوليكشن هي شريكك اللوجستي الأول في اليمن، حيث نربط بين الأسواق العالمية والراحة المحلية. نحن متخصصون في الشراء الدولي والتوصيل الآمن.' },
  brideServices: { en: 'Bride Services', ar: 'خدمات العروسة' },
  brideServicesSubtitle: { en: 'Everything you need for your perfect day', ar: 'كل ما تحتاجينه ليومك المثالي' },
  happyCustomersCount: { en: '2,000+ happy customers', ar: 'أكثر من 2000 عميلة سعيدة' },
  weddingDresses: { en: 'Wedding Dresses', ar: 'فساتين زفاف' },
  accessories: { en: 'Accessories', ar: 'إكسسوارات' },
  makeupArtists: { en: 'Makeup Artists', ar: 'خبيرات تجميل' },
  photography: { en: 'Photography', ar: 'تصوير فوتوغرافي' },
  bridalBouquets: { en: 'Bridal Bouquets', ar: 'مسكات عرائس' },
  weddingPlanning: { en: 'Wedding Planning', ar: 'تنظيم حفلات' },
  invitationsGifts: { en: 'Invitations & Gifts', ar: 'دعوات وهدايا' },
  fromPrice: { en: 'From SAR', ar: 'ابتداءً من' },
  bookNow: { en: 'Book Now', ar: 'احجزي الآن' },
  premiumExperience: { en: 'Premium Shopping Experience', ar: 'تجربة تسوق فاخرة' },
  discoverPremium: { en: 'Discover Premium', ar: 'اكتشف الفخامة' },
  heroSubtitle: { en: 'Your gateway to luxury products, global shopping, and exclusive bridal services — all in one destination.', ar: 'بوابتك للمنتجات الفاخرة، التسوق العالمي، وخدمات العروسة الحصرية — كل ذلك في وجهة واحدة.' },
  exploreNow: { en: 'Explore Now', ar: 'استكشف الآن' },
  countries: { en: 'Countries', ar: 'دولة' },
  ordersDelivered: { en: 'Orders Delivered', ar: 'طلب تم تسليمه' },
  products: { en: 'Products', ar: 'منتج' },
  flashSale: { en: 'Flash Sale', ar: 'عروض خاطفة' },
  flashSaleSubtitle: { en: 'Limited time offers — grab them before they\'re gone!', ar: 'عروض لفترة محدودة — سارع بالحصول عليها قبل نفاذ الكمية!' },
  saleEndsIn: { en: 'Sale ends in', ar: 'ينتهي العرض خلال' },
  hours: { en: 'Hours', ar: 'ساعة' },
  minutes: { en: 'Minutes', ar: 'دقيقة' },
  seconds: { en: 'Seconds', ar: 'ثانية' },
  shopAnywhere: { en: 'By one click, order arrives to your door', ar: 'بضغطة زر يوصل طلبك من العالم لباب بيتك' },
  heroDesc: { en: 'Comprehensive logistics. Shop global • Pay local • Track easy', ar: 'خدمات لوجستية شاملة وموحدة لليمن. تسوّق عالميا • ادفع محليًا • وتتبع طلبك بكل سهولة' },
  logisticsYemen: { en: 'Unified Logistics Services in Yemen', ar: 'خدمات لوجستية موحدة في اليمن' },
  howToOrder: { en: 'How to Buy?', ar: 'كيفية الشراء؟' },
  hotDeals: { en: 'Flash Offers', ar: 'عروض حصرية' },
  specialOffers: { en: 'Special Price', ar: 'سعر خاص' },
  step1Title: { en: 'Pick Store & Item', ar: 'اختر المتجر والمنتج' },
  step1Desc: { en: 'Browse your favorite global store and copy the product link.', ar: 'تصفح متجرك العالمي المفضل وانسخ رابط المنتج الذي تريده.' },
  step2Title: { en: 'Review & Pricing', ar: 'المراجعة والتسعير' },
  step2Desc: { en: 'We will review your link and set the final price for you.', ar: 'سنقوم بمراجعة الرابط وتحديد السعر النهائي لك.' },
  step3Title: { en: 'Local Payment', ar: 'دفع محلي آمن' },
  step3Desc: { en: 'Confirm and pay via Kuraimi, OneCash or Jeeb Wallet.', ar: 'أكد طلبك وادفع عبر الكريمي، ون كاش، أو محفظة جيب.' },
  step4Title: { en: 'Track Order', ar: 'تتبع طلبك حتى وصولها' },
  step4Desc: { en: 'Track your package from warehouses to your door in Yemen.', ar: 'تابع شحنتك من المخازن العالمية حتى وصولها لباب بيتك في اليمن.' },
  login: { en: 'Login', ar: 'دخول' },
  signup: { en: 'Sign Up', ar: 'إنشاء حساب' },
  logout: { en: 'Logout', ar: 'خروج' },
  cart: { en: 'My Cart', ar: 'سلتي' },
  checkout: { en: 'Checkout', ar: 'الدفع' },
  total: { en: 'Total', ar: 'المجموع' },
  emptyCart: { en: 'Your cart is empty', ar: 'سلتك فارغة' },
  trackOrder: { en: 'Track Order', ar: 'تتبع طلبك' },
  officialStore: { en: 'Official Site', ar: 'الموقع الرسمي' },
  localStore: { en: 'Collection Store', ar: 'متجر كوليكشن' },
  googleLogin: { en: 'Login with Google', ar: 'الدخول بحساب جوجل' },
  whatsappSupport: { en: 'WhatsApp Support', ar: 'الدعم الفني' },
  restricted: { en: 'Please login first', ar: 'يرجى تسجيل الدخول أولاً' },
  addToCart: { en: 'Add to Cart', ar: 'إضافة للسلة' },
  selectSize: { en: 'Select Size', ar: 'اختر المقاس' },
  selectColor: { en: 'Select Color', ar: 'اختر اللون' },
  allProducts: { en: 'All Items', ar: 'جميع المنتجات' },
  orderSuccess: { en: 'Order Successful', ar: 'تم الطلب بنجاح' },
  orderNumber: { en: 'Order Number', ar: 'رقم الطلب' },
  copied: { en: 'Copied!', ar: 'تم النسخ!' },
  copyId: { en: 'Copy ID', ar: 'نسخ الرقم' },
  visaMada: { en: 'Visa / Mada', ar: 'فيزا / مدى' },
  localYemen: { en: 'Local Payment', ar: 'دفع محلي' },
  kuraimi: { en: 'Kuraimi Bank', ar: 'بنك الكريمي' },
  jeeb: { en: 'Jeeb Wallet', ar: 'محفظة جيب' },
  onecash: { en: 'One Cash', ar: 'ون كاش' },
  track: { en: 'Track', ar: 'تتبع' },
  orderNotFound: { en: 'Order not found', ar: 'الطلب غير موجود' },
  adminDashboard: { en: 'Dashboard', ar: 'لوحة التحكم' },
  manageOrders: { en: 'Manage Orders', ar: 'إدارة الطلبات' },
  status_pending: { en: 'Reviewing', ar: 'قيد المراجعة' },
  status_purchased: { en: 'Purchased', ar: 'تم الشراء' },
  status_shipped: { en: 'Shipped', ar: 'تم الشحن' },
  status_yemen: { en: 'In Yemen', ar: 'وصل اليمن' },
  status_delivery: { en: 'Delivering', ar: 'قيد التوصيل' },
  status_completed: { en: 'Delivered', ar: 'تم التسليم' },
  status_cancelled: { en: 'Cancelled', ar: 'ملغي' },
  status_awaiting_quote: { en: 'Awaiting Quote', ar: 'بانتظار التسعير' },
  status_quote_ready: { en: 'Quote Ready - Please Pay', ar: 'تم التسعير - يرجى الدفع' },
  requestQuote: { en: 'Request Quote', ar: 'طلب تسعير' },
  howToShopToday: { en: 'How would you like to shop today?', ar: 'كيف تحب أن تتسوق اليوم؟' },
  internationalShopping: { en: 'International Shopping', ar: 'التسوق من المواقع العالمية' },
  fromWorldToDoor: { en: 'From the world to your door', ar: 'من العالم إلى باب بيتك' },
  internationalDesc: { en: 'We order for you from any global store and deliver to Yemen with local payment and full tracking.', ar: 'نطلب لك من أي متجر عالمي ونوصله إلى اليمن مع دفع محلي وتتبع كامل.' },
  orderFromAbroad: { en: 'Order from abroad', ar: 'اطلب من الخارج' },
  readyForDelivery: { en: 'Ready for Delivery', ar: 'منتجات جاهزة للتسليم' },
  wantSomethingFast: { en: 'Want something fast?', ar: 'تبي شي يوصل بسرعة؟' },
  readyDesc: { en: 'Brand perfumes ready for immediate delivery within Yemen.', ar: 'عطور ماركات جاهزة للتسليم الفوري داخل اليمن.' },
  shopNow: { en: 'Shop Now', ar: 'تسوق الآن' },
  brideSection: { en: 'Bride Section', ar: 'قسم العروسة' },
  readyForNewStage: { en: 'Ready for a new stage?', ar: 'جاهزة لمرحلة جديدة؟' },
  brideDesc: { en: 'All the bride\'s needs in one place - complete organization and ease of choice.', ar: 'كل احتياجات العروسة في مكان واحد – تنظيم كامل وسهولة اختيار.' },
  startPreparing: { en: 'Start Preparing', ar: 'ابدأ التجهيز' },
  howServiceWorks: { en: 'How the service works', ar: 'كيف تعمل الخدمة' },
  step1: { en: 'Send product link', ar: 'أرسل رابط المنتج' },
  step2: { en: 'We buy and ship', ar: 'نقوم بالشراء والشحن' },
  step3: { en: 'Receive and pay locally', ar: 'تستلم وتدفع محليًا' },
  whyOrderWithUs: { en: 'Why order with us?', ar: 'ليش تطلب معنا؟' },
  localPaymentOnDelivery: { en: 'Local payment on delivery', ar: 'دفع محلي عند الاستلام' },
  fullTracking: { en: 'Full order tracking', ar: 'تتبع كامل للطلب' },
  directWhatsappSupport: { en: 'Direct WhatsApp support', ar: 'دعم مباشر عبر واتساب' },
  fastCustomerService: { en: 'Fast customer service', ar: 'خدمة عملاء سريعة' },
  easyReturn: { en: 'Return if there\'s a problem', ar: 'استرجاع في حال وجود مشكلة' },
  noBankCardNeeded: { en: 'No bank card needed - Cash on delivery', ar: 'لا تحتاج بطاقة بنكية – الدفع عند الاستلام' },
  siteIdentity: { en: 'Logistics services company and purchasing intermediary from global stores within Yemen.', ar: 'شركة خدمات لوجستية ووسيط شراء من المتاجر العالمية داخل اليمن.' },
  customerReviews: { en: 'Customer Reviews', ar: 'تقييمات العملاء' },
  addReview: { en: 'Add your review', ar: 'أضف تقييمك' },
  completedOrders: { en: 'Completed Orders', ar: 'الطلبات المنجزة' },
  happyCustomers: { en: 'Happy Customers', ar: 'عملاء سعداء' },
  offers: { en: 'Offers', ar: 'العروض' },
  viewAll: { en: 'View All', ar: 'عرض الكل' },
  quickLinks: { en: 'Quick Links', ar: 'روابط سريعة' },
  supportedStores: { en: 'Supported Stores', ar: 'المتاجر المدعومة' },
  contactUs: { en: 'Contact Us', ar: 'تواصل معنا' },
  location: { en: 'Yemen - Ibb', ar: 'اليمن - إب' },
  favorites: { en: 'Favorites', ar: 'المفضلة' },
  notifications: { en: 'Notifications', ar: 'الإشعارات' },
  noNotifications: { en: 'No Notifications', ar: 'لا توجد إشعارات' },
  viewAllServices: { en: 'View All Services', ar: 'عرض كل الخدمات' },
  discoverOffers: { en: 'Discover the best exclusive offers and discounts', ar: 'اكتشف أفضل العروض والخصومات الحصرية' },
  startShoppingNow: { en: 'START SHOPPING NOW', ar: 'ابدأ التسوق الآن' },
  certifiedStores: { en: 'CERTIFIED GLOBAL STORES', ar: 'المتاجر العالمية المعتمدة' },
  home: { en: 'Home', ar: 'الرئيسية' },
  shop: { en: 'Shop', ar: 'المتجر' },
  bride: { en: 'Bride', ar: 'العروسة' },
  tracking: { en: 'Tracking', ar: 'تتبع طلبك' },
  admin: { en: 'Admin', ar: 'الإدارة' },
  account: { en: 'Account', ar: 'حسابي' },
  brideSubtitle: { en: 'Complete Bride Preparation', ar: 'تجهيزات العروسة المتكاملة' },
  searchBride: { en: 'Search in Bride section...', ar: 'بحث في قسم العروسة...' },
  noBrideProducts: { en: 'No Items in this Section', ar: 'لا توجد منتجات في هذا القسم' },
  share: { en: 'Share', ar: 'مشاركة' },
  linkCopied: { en: 'Link copied!', ar: 'تم نسخ الرابط!' },
  flashSaleTitle: { en: 'Flash Sale', ar: 'عروض خاطفة' },
  specialOffersTitle: { en: 'Special Offers', ar: 'عروض خاصة' },
  catalogSubtitle: { en: 'Curated collections for your style.', ar: 'مجموعات حصرية تم اختيارها لك.' },
  search: { en: 'Search...', ar: 'بحث...' },
  collections: { en: 'Collections', ar: 'الأقسام' },
  noProducts: { en: 'No Items Found', ar: 'لا توجد منتجات' },
  accessingStore: { en: 'Accessing Store...', ar: 'جاري الدخول إلى المتجر...' },
  enterOrderId: { en: 'Enter your global order reference ID', ar: 'أدخل رقم الطلب العالمي الخاص بك' },
  recentOrders: { en: 'My Recent Orders', ar: 'طلباتي الأخيرة' },
  date: { en: 'DATE', ar: 'التاريخ' },
  items: { en: 'ITEMS', ar: 'الأصناف' },
  productsCount: { en: 'Product(s)', ar: 'منتجات' },
  paymentMethod: { en: 'PAYMENT METHOD', ar: 'وسيلة الدفع' },
  totalValue: { en: 'TOTAL VALUE', ar: 'إجمالي القيمة' },
  refresh: { en: 'Refresh', ar: 'تحديث' },
  orderDetails: { en: 'Order Details', ar: 'تفاصيل الطلب' },
  awaitingQuote: { en: 'Awaiting Quote', ar: 'بانتظار التسعير' },
  viewLink: { en: 'View Link', ar: 'رابط المنتج' },
  awaitingPricingDesc: { en: 'Our team is reviewing your links to set the final price. You will be notified once it is ready.', ar: 'يقوم فريقنا بمراجعة الروابط لتحديد السعر النهائي. سيتم إشعارك فور جاهزية التسعيرة.' },
  quoteReadyTitle: { en: 'Quote Ready - Please Pay', ar: 'التسعيرة جاهزة - يرجى الدفع' },
  quoteReadyDesc: { en: 'The price has been set. Please pay via Kuraimi, OneCash or Jeeb and send the receipt.', ar: 'تم تحديد السعر. يرجى الدفع عبر الكريمي، ون كاش أو جيب وإرسال الإيصال.' },
  sendReceipt: { en: 'Send Payment Receipt', ar: 'إرسال إيصال الدفع' },
  whatsappPaymentMsg: { en: 'Hello, I want to confirm payment for order: ', ar: 'مرحباً، أرغب في تأكيد الدفع للطلب رقم: ' },
  whatsappPaymentTotal: { en: '. Total: ', ar: '. المجموع: ' },
  whatsappPaymentCurrency: { en: ' SAR.', ar: ' ريال.' }
};
